# Autogenerated with SMOP version 0.23
# main.py ksc_toy/dhat.m -o ksc_toy/dhat.py
from __future__ import division
import numpy as np
from scipy.io import loadmat,savemat
import os

def dhat(x, y):
    alpha = np.dot(x, y.T) / (np.dot(y, y.T))
    dist = norm(x - np.dot(alpha, y)) / norm(x)
    return dist
